# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x07\n\x05\x45mpty\"\xc1\x01\n\x0fService1Request\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x03(\t\x12 \n\x06status\x18\x06 \x01(\x0e\x32\x10.Status_Service1\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x10\n\x08\x64ocument\x18\x08 \x01(\tB\x05\n\x03_id\"\x9d\x01\n\x0fService2Request\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x03(\t\x12 \n\x06status\x18\x06 \x01(\x0e\x32\x10.Status_Service2B\x05\n\x03_id\"u\n\x0fService3Request\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x03(\t\x12\x10\n\x08\x64ocument\x18\x05 \x01(\t\"c\n\x0fService4Request\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x03(\t*O\n\x0fStatus_Service1\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05\x46IRED\x10\x01\x12\x19\n\x15TEMPORARY_NOT_WORKING\x10\x02\x12\t\n\x05WORKS\x10\x03*:\n\x0fStatus_Service2\x12\r\n\tDEFAULT_2\x10\x00\x12\x0b\n\x07WORKS_2\x10\x01\x12\x0b\n\x07\x46IRED_2\x10\x02\x32\xa3\x01\n\tMyService\x12$\n\x08Service1\x12\x10.Service1Request\x1a\x06.Empty\x12$\n\x08Service2\x12\x10.Service2Request\x1a\x06.Empty\x12$\n\x08Service3\x12\x10.Service3Request\x1a\x06.Empty\x12$\n\x08Service4\x12\x10.Service4Request\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS_SERVICE1']._serialized_start=603
  _globals['_STATUS_SERVICE1']._serialized_end=682
  _globals['_STATUS_SERVICE2']._serialized_start=684
  _globals['_STATUS_SERVICE2']._serialized_end=742
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_SERVICE1REQUEST']._serialized_start=28
  _globals['_SERVICE1REQUEST']._serialized_end=221
  _globals['_SERVICE2REQUEST']._serialized_start=224
  _globals['_SERVICE2REQUEST']._serialized_end=381
  _globals['_SERVICE3REQUEST']._serialized_start=383
  _globals['_SERVICE3REQUEST']._serialized_end=500
  _globals['_SERVICE4REQUEST']._serialized_start=502
  _globals['_SERVICE4REQUEST']._serialized_end=601
  _globals['_MYSERVICE']._serialized_start=745
  _globals['_MYSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
